#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell available, you may
#       specify it by setting the SHELL variable when running this script. For
#       example:
#
#           SHELL=/bin/bash ./gradlew
#
#   Busybox and similar reduced shells will NOT work, because this script
#   requires all of these POSIX shell features:
#     * functions;
#     * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#       «${var#pattern}», «${var%pattern}»;
#     * compound commands having a "then" clause, i.e. «if [ condition ] ; then
#       setups inside.
#     * various built-in commands including «command», «set», and «local»
#
#   Important for patching:
#
#   (1) This script targets any POSIX shell, so avoiding extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       single string and using $1, $2, etc. relies on very poor shell (e.g. sh) parsing that:
#         * fails when a parameter contains spaces, a comma or an equals sign
#         * requires careful quoting when calling other programs via variables
#         * will do surprising things with parameters that get re-expanded, escaped,
#           and double-escaped through multiple levels of the shell.
#
#       This is why all expansions in this script are protected with double quotes.
#

##############################################################################
#
#   Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS
#   to pass JVM options to this script.
#
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

##############################################################################
#
#   Determine the Java command to use to start the JVM.
#
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        echo "Please set the JAVA_HOME variable in your environment to match the" >&2
        echo "location of your Java installation." >&2
        exit 1
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || {
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
        echo "Please set the JAVA_HOME variable in your environment to match the" >&2
        echo "location of your Java installation." >&2
        exit 1
    }
fi

##############################################################################
#
#   Increase the maximum file descriptors if we can.
#
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $OSTYPE in
        cygwin*|msys*)
            darwin=false
            cygwin=true
            ;;
        darwin*)
            darwin=true
            cygwin=false
            ;;
        nonstop*)
            nonstop=true
            cygwin=false
            ;;
        *)
            darwin=false
            cygwin=false
            nonstop=false
            ;;
    esac

    if [ "$darwin" = false -a "$cygwin" = false -a "$nonstop" = false ] ; then
        case $( ulimit -H -n ) in
          '*unlimited'|2147483647|33554432) :
              ;;
          *)
              { echo ""; echo "WARNING: Reach file descriptor limit ($( ulimit -H -n )), consider setting DEFAULT_JVM_OPTS=\"\$DEFAULT_JVM_OPTS -Dfile.encoding=UTF-8\""; echo ""; }
              ;;
        esac
    fi
fi

# Add default scheme and host if JAVA_OPTS is empty
if [ -z "$JAVA_OPTS" ]; then
    JAVA_OPTS=$DEFAULT_JVM_OPTS
fi

# Escape application name to make it look nicer.
APP_NAME="Gradle"
APP_HOME_RELATIVE=.
if [ -L "$0" ]
then
    APP_HOME=$( cd "$( dirname "$0" )" && pwd -P )
    APP_HOME_RELATIVE=$( cd "$( dirname "$0" )" && pwd -P )
else
    APP_HOME=$( cd "$( dirname "$0" )/.." && pwd -P )
    APP_HOME_RELATIVE=$( cd "$( dirname "$0" )/.." && pwd -P )
fi

##############################################################################
#
#   Determine the Java command to use to start the JVM.
#
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        echo "Please set the JAVA_HOME variable in your environment to match the" >&2
        echo "location of your Java installation." >&2
        exit 1
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || {
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
        echo "Please set the JAVA_HOME variable in your environment to match the" >&2
        echo "location of your Java installation." >&2
        exit 1
    }
fi

exec "$JAVACMD" $JAVA_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
